select *
where {
    <http://lingbm.linkeddata.es/vendor/%vendorID%> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Vendor> .
    <http://lingbm.linkeddata.es/vendor/%vendorID%> <http://www.example.com/offers> ?offer .
    ?offer <http://www.example.com/product> ?product .
    ?product <http://www.example.com/producer> ?producer .
    ?producer <http://www.example.com/country> ?country .
    ?country <http://www.example.com/code> ?countryCode .
}
