select * where {
    <http://lingbm.linkeddata.es/offer/12519> a <http://schema.org/Offer> .
    <http://lingbm.linkeddata.es/offer/12519> <http://www.example.com/productWithReviews> ?product .
    ?product <http://www.example.com/reviews> ?review .
    ?review <http://www.example.com/title> ?reviewTitle .
    ?review <http://www.example.com/text> ?reviewText .
    ?review <http://www.example.com/reviewDate> ?reviewDate .
    ?review <http://www.example.com/publishDate> ?reviewPublishDate .
    ?review <http://www.example.com/rating1> ?reviewRating1 .
    ?review <http://www.example.com/rating2> ?reviewRating2 .
}
